"""return case id is nullable

Revision ID: 0c865dbcab69
Revises: a8a470857cbc
Create Date: 2025-08-27 03:50:58.728781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c865dbcab69'
down_revision = 'a8a470857cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)

    # ### end Alembic commands ###
