"""serial number

Revision ID: 0f11900b07e6
Revises: 
Create Date: 2025-07-15 16:33:28.261511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f11900b07e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('overload', 'door_detector', 'control_unit', name='producttypeenum'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'user', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('return_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'awaiting_parts', 'repaired', 'shipped', 'closed', name='casestatusenum'), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('receipt_method', sa.Enum('shipment', 'in_person', name='receiptmethodenum'), nullable=False),
    sa.Column('fault_source', sa.Enum('our_firm', 'customer', 'unknown', name='faultsourceenum'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.String(length=254), nullable=True),
    sa.Column('warranty_status', sa.Enum('in_warranty', 'out_of_warranty', 'unknown', name='warrantystatusenum'), nullable=False),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.Enum('paid', 'unpaid', 'waived', name='paymentstatusenum'), nullable=True),
    sa.Column('shipping_info', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.email'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_cases_arrival_date'), ['arrival_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_cases_assigned_user_id'), ['assigned_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_cases_status'), ['status'], unique=False)

    op.create_table('return_case_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_case_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('overload', 'door_detector', 'control_unit', name='producttypeenum'), nullable=False),
    sa.Column('product_model_id', sa.Integer(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('is_main_product', sa.Boolean(), nullable=False),
    sa.Column('attached_to_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attached_to_item_id'], ['return_case_items.id'], ),
    sa.ForeignKeyConstraint(['product_model_id'], ['product_models.id'], ),
    sa.ForeignKeyConstraint(['return_case_id'], ['return_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_case_items')
    with op.batch_alter_table('return_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_return_cases_status'))
        batch_op.drop_index(batch_op.f('ix_return_cases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_return_cases_assigned_user_id'))
        batch_op.drop_index(batch_op.f('ix_return_cases_arrival_date'))

    op.drop_table('return_cases')
    op.drop_table('users')
    op.drop_table('product_models')
    op.drop_table('customers')
    # ### end Alembic commands ###
