"""Create all tables

Revision ID: 2852193bd1e6
Revises: 
Create Date: 2025-07-04 17:00:55.375789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2852193bd1e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('warranty_status_photosensor', sa.Enum('valid', 'expired', 'unknown', name='warrantystatus'), nullable=True),
    sa.Column('photosensor_height_count', sa.Integer(), nullable=False),
    sa.Column('photosensor_power_count', sa.Integer(), nullable=False),
    sa.Column('warranty_status_overload', sa.Enum('valid', 'expired', 'unknown', name='warrantystatus'), nullable=True),
    sa.Column('overload_lc1_count', sa.Integer(), nullable=False),
    sa.Column('performed_service', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_details', sa.Enum('paid', 'unpaid', 'pending', name='paymentstatus'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='casestatus'), nullable=True),
    sa.Column('shipping_company', sa.String(length=100), nullable=True),
    sa.Column('shipping_date', sa.Date(), nullable=True),
    sa.Column('shipping_addresses', sa.Text(), nullable=True),
    sa.Column('shipping_information', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'user', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=128), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'EDIT', name='useractionpermission'), nullable=False),
    sa.Column('field_name', sa.Enum('ARRIVAL_DATE', 'REPRESENTATIVE_NAME', 'CONTACT_INFORMATION', 'ADDRESS_DETAILS', 'NOTES', 'WARRANTY_STATUS_PHOTOSENSOR', 'PHOTOSENSOR_HEIGHT_COUNT', 'PHOTOSENSOR_POWER_COUNT', 'WARRANTY_STATUS_OVERLOAD', 'OVERLOAD_LC1_COUNT', 'PERFORMED_SERVICE_DESCRIPTION', 'COST_AMOUNT', 'PAYMENT_DETAILS_STATUS', 'CASE_STATUS', 'SHIPPING_COMPANY_NAME', 'SHIPPING_DATE_INFO', 'SHIPPING_ADDRESSES_DETAILS', 'SHIPPING_INFORMATION_DETAILS', name='userfieldpermission'), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_permissions')
    op.drop_table('users')
    op.drop_table('cases')
    # ### end Alembic commands ###
