"""Initial

Revision ID: 2a53ab2eef11
Revises: 
Create Date: 2025-08-15 16:48:45.289306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a53ab2eef11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('invitation_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invited_by', sa.String(length=254), nullable=True))
        batch_op.add_column(sa.Column('invitation_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['invited_by'], ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invitation_sent_at')
        batch_op.drop_column('invited_by')
        batch_op.drop_column('invitation_expiry')
        batch_op.drop_column('invitation_token')

    # ### end Alembic commands ###
