"""Delete yapilan_islemler

Revision ID: 45c240e7616e
Revises: 2e50b347b468
Create Date: 2025-09-07 23:12:28.657915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45c240e7616e'
down_revision = '2e50b347b468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_case_items', schema=None) as batch_op:
        batch_op.drop_column('yapilan_islemler')

    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)

    with op.batch_alter_table('return_case_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yapilan_islemler', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
