"""add_cost_fields_to_return_case_remove_from_items

Revision ID: 538b15350f4c
Revises: cea3b5923114
Create Date: 2025-08-12 00:00:56.262837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '538b15350f4c'
down_revision: Union[str, Sequence[str], None] = 'cea3b5923114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_case_items', 'cost')
    op.add_column('return_cases', sa.Column('yedek_parca', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('return_cases', sa.Column('bakim', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('return_cases', sa.Column('iscilik', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('return_cases', sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_cases', 'cost')
    op.drop_column('return_cases', 'iscilik')
    op.drop_column('return_cases', 'bakim')
    op.drop_column('return_cases', 'yedek_parca')
    op.add_column('return_case_items', sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
