"""Add UserActionLog table for tracking return case changes

Revision ID: 9164c4877691
Revises: e4b0358dd420
Create Date: 2025-08-27 00:38:54.975991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9164c4877691'
down_revision = 'e4b0358dd420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('field_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('field_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
