"""initial migration

Revision ID: a174c669d808
Revises: 
Create Date: 2025-09-07 21:27:52.995890

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a174c669d808'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_cases', schema=None) as batch_op:
        batch_op.drop_constraint('return_cases_email_thread_id_key', type_='unique')
        batch_op.drop_column('email_thread_id')

    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=254),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('user_email',
               existing_type=sa.VARCHAR(length=254),
               nullable=True)

    with op.batch_alter_table('return_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_thread_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('return_cases_email_thread_id_key', ['email_thread_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
