"""Initial

Revision ID: a78f0ccdc623
Revises: 2a53ab2eef11
Create Date: 2025-08-15 17:09:37.531586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a78f0ccdc623'
down_revision = '2a53ab2eef11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('invitation_sent_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('invited_at')

    # ### end Alembic commands ###
