"""Add UserActionLog table for tracking return case changes

Revision ID: a8a470857cbc
Revises: 9164c4877691
Create Date: 2025-08-27 01:32:26.159582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a470857cbc'
down_revision = '9164c4877691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_info', sa.String(length=255), nullable=True))
        batch_op.drop_column('old_value')
        batch_op.drop_column('new_value')
        batch_op.drop_column('description')
        batch_op.drop_column('field_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_name', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('additional_info')

    # ### end Alembic commands ###
