"""add_yapilan_islemler_field

Revision ID: cea3b5923114
Revises: d146199eea1c
Create Date: 2025-08-11 23:28:57.316353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea3b5923114'
down_revision: Union[str, Sequence[str], None] = 'd146199eea1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_case_items', sa.Column('yapilan_islemler', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_case_items', 'yapilan_islemler')
    # ### end Alembic commands ###
