"""removed services

Revision ID: e431dbed91f8
Revises: 45c240e7616e
Create Date: 2025-09-08 00:39:28.087800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e431dbed91f8'
down_revision = '45c240e7616e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_case_items', schema=None) as batch_op:
        batch_op.drop_column('service_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_case_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_type', postgresql.ENUM('maintenance', 'repair', 'calibration', name='servicetypeenum'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
