"""Initial migration

Revision ID: e4b0358dd420
Revises: 
Create Date: 2025-08-26 22:55:46.702714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b0358dd420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_action_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=254), nullable=False),
    sa.Column('return_case_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'STAGE_COMPLETE', 'FIELD_EDIT_AFTER_COMPLETION', name='actiontype'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['return_case_id'], ['return_cases.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_action_logs')
    # ### end Alembic commands ###
