"""Initial database schema

Revision ID: fd6f571acb9f
Revises: 
Create Date: 2025-08-20 15:00:13.142666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6f571acb9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_cases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_thread_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email_thread_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_thread_id')

    # ### end Alembic commands ###
